### ISSUE TITLE
Stepwise generation of a deck?

### ISSUE THREAD

**Issue by PhD-AR** [brunopacheco1/lod-anki#56]
Hello, given a list of Luxembourgish words, how do I generate the .apkg file for anki.
Say this is my list:
Spanish Word /  Luxembourgish
hola                       moien
bueno                    gutt
mal                        schlecht

Lets say I want the spanish word in the front and the Luxembourgish one in the back?

I tried with csv file but it did not work...

How do I input this list to the app so that it generates the deck for anki?

I could not find the documentation for this but if there is documentation with this info please let me know. I am very keen to use this app and promote it with my colleagues once I am able to generate my first decks...  

[edit typo]

**Comment by brunopacheco1** [comment]
Hello.

This project is not an exporting tool from a file format to apkg. The software will try to find the word in the LOD.lu data and expose it as a flashcard. The front is the word you want to learn, and the back is the word description, as it's from LOD.lu.

Here is an example of an input file to generate a deck using this project.

https://github.com/brunopacheco1/lod-anki/blob/main/decks/definitions/schwatzt_dir_letzebuergesh/per_book/a1.json

As you can see, it's a JSON file containing the flashcards (or the words in Luxembourgish) you want to export and the languages you wish to output. Currently, LOD provides outputs in German, English, French, and Portuguese.

In order to reduce the scope of this project and provide reliable content, I  did not want to connect to external providers to translate and match words.

**Comment by brunopacheco1** [comment]
I tried to explain how to build a deck file, I hope now it's clearer. Please, let me know if lod-anki fits what you need. Or perhaps we can work together on something.

**Comment by PhD-AR** [comment]
Okay, got it. The thing is that the scope of the tool was not very clear to me at first. I ran the help command but still did not get it. 
Now I understand, it is clear to me that the tool generates the anki package file with the flascards in which the front is the word alone in Luxembourgish and the back is the definition and pronunciation.

Great tool. Thanks a lot!

**Comment by brunopacheco1** [comment]
Thanks a lot for the question, I believe I can close it.

Btw, I would appreciate it if you provide feedback, especially on the Anki output.
